# from name: plasmabio-template-r

name: M1MEG-UE1-TP5-R
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - jupyterlab=2
  - nbresuse
  - nodejs
  - libgomp
  - glib=2.56
  - r-irkernel
  - r-base>=3.6
  - r-tidyverse 
  - r-Matrix
  - r-lattice
  - r-fdrtool
  - r-rpart
  - r-RSQLite
  - r-ggplot2
  
  # - r-biocmanager
  # - r-bioconductor-biostrings
  # - r-bioconductor-biobase
  # - r-bioconductor-limma
  # - r-bioconductor-affy
  # - r-bioconductor-affyplm
  # - r-bioconductor-simpleaffy
  # - r-bioconductor-genefilter
  
# Leslignes suviantes ont les essais successifs pour faire tourner la normalisation gcrma qui donne une erreur ERROR; return code from pthread_create() is 22
# à l'étape de normalisation  
#  - libopenblas=0.3.3  ne marche pas
#  - libopenblas ne marche pas
#  - libblas  ne marche pas
#  - glib=2.56 en cours
