name: plasmabio-template-r
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - jupyterlab=2
  - nbresuse
  - nodejs
  - libgomp
  - libopenblas=0.3.3
  - r-irkernel
  - r-base>=3.6
  - r-tidyverse 
  - r-Matrix
  - r-lattice
  - r-fdrtool
  - r-rpart
  - r-RSQLite
  - r-ggplot2
  
  #après tidyverse, packages qui s'installent ok si on les mets depuis le postBuild
