# from name: plasmabio-template-r

name: M1MEG-UE1-TP5-R
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - jupyterlab=2
  - nbresuse
  - nodejs
  - libgomp
  - libblas
  - r-irkernel
  - r-base>=3.6
  - r-tidyverse 
  - r-Matrix
  - r-lattice
  - r-fdrtool
  - r-rpart
  - r-RSQLite
  - r-ggplot2
  
  # - r-biocmanager
  # - r-bioconductor-biostrings
  # - r-bioconductor-biobase
  # - r-bioconductor-limma
  # - r-bioconductor-affy
  # - r-bioconductor-affyplm
  # - r-bioconductor-simpleaffy
  # - r-bioconductor-genefilter
  
#  - libopenblas=0.3.3  ne marche pas
#  - libopenblas ne marche pas
#  - libblas  en cours
#  - glib=2.56
